# Generated by Django 5.2.15 on 2026-06-27 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingMegaSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount', models.IntegerField(help_text='Enter discount percentage, e.g. 30')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.clothingbrand')),
            ],
        ),
    ]
