# Generated by Django 5.2.15 on 2026-07-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_clothingbrand_image_url_foodcentre_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingbrand',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='clothing/'),
        ),
        migrations.AddField(
            model_name='foodcentre',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='food/'),
        ),
        migrations.AddField(
            model_name='localevent',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='other',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='others/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='recipes/'),
        ),
        migrations.AddField(
            model_name='upcomingmegasale',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='sales/'),
        ),
    ]
